### ISSUE TITLE
[1.14.4] Line of code causing a crash

### ISSUE THREAD

**Issue by LexxieSlevaskos** [TheLMiffy1111/JAOPCA#146]
Here is my log, I had someone else to review it apparently in their research one of the lines caused the crash.
[latest.log](https://github.com/TheLMiffy1111/JAOPCA/files/4263244/latest.log)

**Comment by Vaelzan** [comment]
I should add a link to the actual code:
https://github.com/TheLMiffy1111/JAOPCA/blob/1.14/src/main/java/thelm/jaopca/data/DataCollector.java#L64

That line assumes that the resource locations that are returned will always have a slash in them (other than the one directly after "tags"). While this is normally the case, it isn't always (a file might just be tags/blah.json, rather than tags/blocks/blah.json in some unusual situations). It just needs a basic safety check added.

**Comment by TheLMiffy1111** [comment]
Fixed
