### ISSUE TITLE
Black Quartz oddities

### ISSUE THREAD

**Issue by xbony2** [TheLMiffy1111/JAOPCA#36]
Actually Additions Black Quartz drops as an ore and must be smelted to become Black Quartz or be crushed into Crushed Black Quartz and then smelted. So, it acts kind of like a regular ore, but Black Quartz is registered as "gemQuartzBlack" so there's no IC2 Crushed Ores registered for it. Is it possible to get these registered?

Also, the stuff registered by JAOPCA, like "Quartz Black Gear," has a weird autogenerated name. I think in AOBA names could be adjusted in the config; could you add a similar option (or some sort of support) to JAOPCA?

Thanks for your time ^_^

**Comment by TheLMiffy1111** [comment]
I currently do not register gems in the IC2 module, because its ore processing does not support gems, and I could not find any addons that do so. If you want a black quartz support for IC2, you might need to do them yourself. (Or you could do some tinkering with OreDictInit and register black quartz as ingots)
Also names can be changed with the localization files, I will add the correct name for black quartz in an update.

**Comment by xbony2** [comment]
The problem is that it doesn't act like a gem :c maybe I will see if I can register it.

Thanks

**Comment by TimGoll** [comment]
maybe report to actually additions

**Comment by TheLMiffy1111** [comment]
gonna close this
