### ISSUE TITLE
[1.12.2] Custom Textures

### ISSUE THREAD

**Issue by AcidKat** [TheLMiffy1111/JAOPCA#43]
Any chance I can have JAOPCA apply textures from a resource pack to specific items?

I'm aware there's a template that exists in the mod that it uses to generate textures, but I'd like there to be some way to make custom ones that override these generates ones if possible.

**Comment by TheLMiffy1111** [comment]
Currently due to the way the mod works, JAOPCA cannot use custom textures for very specific items, like if somebody wants separate textures for a certain type of material like Fiery Metal. To add this feature, the mod will need to have some parts re-written, I suppose.

However, if you want the whole set of, like, plates, use another texture, just use a resourcepack.
