### ISSUE TITLE
1.12.2 Fatal Conflict with Zen: Foundry

### ISSUE THREAD

**Issue by TheBeesElise** [TheLMiffy1111/JAOPCA#90]
Game crashes with both Zen:Foundry and JAOPCA loaded while JAOPCA is building its fluid registry. It seems like both mods are trying to create the same fluid for some molten metals

crash report:
https://pastebin.com/ZF6FQ5Z9

**Comment by TheLMiffy1111** [comment]
You might wanna use Ignition: Foundry for now.

**Comment by CrankySupertoonArchive** [comment]
For Clarification, Zen:Foundry is a mod similar to Foundry but made with ceramics. When OP tries to load the pack it is looking for normal foundry not Zen:Fountry.

The Fix?
Add Support for Zen:Foundry too.

**Comment by CrankySupertoonArchive** [comment]
I did fork the mod here and removed Foundry support all togeather so Zen Foundry works. https://minecraft.curseforge.com/projects/jaopca-progreso-fix. The reason this was needed because even if @TheLMiffy1111 tries to fix it, he cannot because its the same code with the same modid. Its like saying (hypothectically if enderio classic exists) im going to take enderio from 1.10 and the 1.12 and all support for them in the same mod. You cannot because duplicate classes exist under the same modid

**Comment by TheLMiffy1111** [comment]
actually fixed it with reflection
